### ISSUE TITLE
Caffemodels and prototxts for MIT67 and SUN397 datasets

### ISSUE THREAD

**Issue by kristellmarisse** [wanglimin/Places205-VGGNet#1]
Can you also share the models and prototxts for MIT67 and SUN397 datasets?

**Comment by wanglimin** [comment]
We did not train caffe models on the datasets of MIT67 and SUN397. We directly use the learned models on Places205 to extract features on the datasets of MIT67 and SUN397. So the prototxts and models are the same the with Places205-VGGNet.

**Comment by kristellmarisse** [comment]
Thanks for the clarification.
